"""
neuro_symbolic_trainer.py
=========================

Panini Language Machine — Neuro-Symbolic Trainer

File 11/14.

Purpose
-------
Turn the symbolic representation produced by paninian_english_llm.py into a
trainable neural side-channel.  The trainer supports three levels:

1. Pure-Python reference training for architectural tests.
2. Optional PyTorch symbolic-bias training.
3. A Transformer-compatible batch contract for future full LLM training.

The central hypothesis is:

    token representation + Paninian structural representation
                              ->
                    neural prediction

and, for attention-based models:

    attention logits + learned/scaled symbolic bias -> attention weights

This file deliberately does not claim to be a production LLM trainer. It is
a research scaffold with inspectable losses, symbolic gates, checkpointing,
and deterministic self-tests.

The trainer can consume either:
    - Paninian English representations generated by File 10, or
    - lightweight JSON records containing input/target text and symbolic bias.

No PyTorch installation is required for the reference path.
"""

from __future__ import annotations

import argparse
import json
import math
import random
import sys
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple

try:
    from paninian_english_llm import VyakaranaGraphAutomata
except ImportError:
    VyakaranaGraphAutomata = None


# ============================================================================
# 1. Configuration
# ============================================================================

@dataclass
class TrainerConfig:
    learning_rate: float = 0.01
    epochs: int = 10
    symbolic_bias_scale: float = 1.0
    symbolic_gate: float = 1.0
    gradient_clip: float = 1.0
    seed: int = 42
    checkpoint_every: int = 5
    warmup_steps: int = 0
    weight_decay: float = 0.0

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class TrainingExample:
    text: str
    target: Optional[str] = None
    symbolic_bias: Optional[List[List[float]]] = None
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class TrainingMetrics:
    epoch: int
    loss: float
    symbolic_loss: float
    baseline_loss: float
    accuracy: float
    symbolic_attention_mass: float

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class TrainingState:
    epoch: int = 0
    step: int = 0
    best_loss: float = float("inf")
    history: List[TrainingMetrics] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "epoch": self.epoch,
            "step": self.step,
            "best_loss": self.best_loss,
            "history": [metric.to_dict() for metric in self.history],
        }


# ============================================================================
# 2. Numerical utilities
# ============================================================================

def softmax(values: Sequence[float]) -> List[float]:
    if not values:
        return []
    maximum = max(values)
    exps = [math.exp(v - maximum) for v in values]
    total = sum(exps)
    if total <= 0:
        return [1.0 / len(values)] * len(values)
    return [v / total for v in exps]


def cross_entropy(probabilities: Sequence[float], target: int) -> float:
    if not probabilities:
        raise ValueError("probabilities cannot be empty")
    if target < 0 or target >= len(probabilities):
        raise IndexError("target index outside probability vector")
    return -math.log(max(probabilities[target], 1e-12))


def argmax(values: Sequence[float]) -> int:
    if not values:
        raise ValueError("cannot argmax empty sequence")
    return max(range(len(values)), key=lambda i: values[i])


def clip(value: float, limit: float) -> float:
    if limit <= 0:
        return value
    return max(-limit, min(limit, value))


def matrix_add(
    left: Sequence[Sequence[float]],
    right: Sequence[Sequence[float]],
    scale: float = 1.0,
) -> List[List[float]]:
    if len(left) != len(right):
        raise ValueError("matrix row counts differ")
    result: List[List[float]] = []
    for a, b in zip(left, right):
        if len(a) != len(b):
            raise ValueError("matrix column counts differ")
        result.append([x + scale * y for x, y in zip(a, b)])
    return result


def row_softmax(matrix: Sequence[Sequence[float]]) -> List[List[float]]:
    return [softmax(row) for row in matrix]


def attention_entropy(row: Sequence[float]) -> float:
    return -sum(
        p * math.log(p, 2)
        for p in row
        if p > 0
    )


def attention_mass_on_symbolic_edges(
    attention: Sequence[Sequence[float]],
    symbolic_bias: Sequence[Sequence[float]],
) -> float:
    """Average attention probability on non-zero symbolic edges."""
    masses: List[float] = []
    for att_row, bias_row in zip(attention, symbolic_bias):
        indices = [i for i, value in enumerate(bias_row) if abs(value) > 1e-12]
        if indices:
            masses.append(sum(att_row[i] for i in indices))
    return sum(masses) / len(masses) if masses else 0.0


# ============================================================================
# 3. Symbolic preprocessing
# ============================================================================

class SymbolicBatchBuilder:
    """Create TrainingExample objects from File 10 representations."""

    def __init__(self, analyzer: Optional[Any] = None) -> None:
        self.analyzer = analyzer
        if self.analyzer is None and VyakaranaGraphAutomata is not None:
            self.analyzer = VyakaranaGraphAutomata()

    def from_text(
        self,
        text: str,
        target: Optional[str] = None,
    ) -> TrainingExample:
        if self.analyzer is None:
            raise RuntimeError(
                "paninian_english_llm.py is required for text-to-symbolic preprocessing"
            )

        representation = self.analyzer.analyze(text)
        return TrainingExample(
            text=text,
            target=target,
            symbolic_bias=representation["Structural_Bias"],
            metadata={
                "action_engine": representation["Action_Engine"],
                "action_engine_index": representation["Action_Engine_Index"],
                "bindings": representation["Bindings"],
                "missing_required_roles": representation["Missing_Required_Roles"],
                "complete_required_frame": representation["Complete_Required_Frame"],
                "atoms": representation["Atoms"],
            },
        )

    def from_json_record(self, record: Mapping[str, Any]) -> TrainingExample:
        text = str(record.get("text") or record.get("input") or "")
        if not text:
            raise ValueError("training record has no text/input field")
        target = record.get("target")
        bias = record.get("symbolic_bias")
        if bias is None:
            representation = self.from_text(text, target=target)
            return representation
        return TrainingExample(
            text=text,
            target=None if target is None else str(target),
            symbolic_bias=[list(map(float, row)) for row in bias],
            metadata=dict(record.get("metadata") or {}),
        )

    def load_jsonl(self, path: str | Path) -> List[TrainingExample]:
        examples: List[TrainingExample] = []
        with Path(path).open("r", encoding="utf-8") as handle:
            for line_number, line in enumerate(handle, start=1):
                line = line.strip()
                if not line:
                    continue
                try:
                    record = json.loads(line)
                    examples.append(self.from_json_record(record))
                except Exception as exc:
                    raise ValueError(
                        f"invalid JSONL record at line {line_number}: {exc}"
                    ) from exc
        return examples


# ============================================================================
# 4. Reference symbolic model
# ============================================================================

class ReferenceNeuroSymbolicModel:
    """
    Tiny differentiable-by-hand model used to validate the architecture.

    It learns a scalar symbolic gate and a set of token-class logits.
    This is NOT intended to compete with a Transformer. It makes the training
    mechanics visible and testable before adding a full neural backbone.
    """

    def __init__(
        self,
        vocabulary: Sequence[str],
        seed: int = 42,
    ) -> None:
        self.vocabulary = list(vocabulary)
        self.index = {token: i for i, token in enumerate(self.vocabulary)}
        rng = random.Random(seed)
        self.bias_gate = 0.5
        self.token_bias = [
            rng.uniform(-0.05, 0.05)
            for _ in self.vocabulary
        ]

    def logits(
        self,
        base_logits: Sequence[float],
        symbolic_score: float,
    ) -> List[float]:
        if len(base_logits) != len(self.vocabulary):
            raise ValueError("base logits and vocabulary have different sizes")
        return [
            float(base) + self.token_bias[i] + self.bias_gate * symbolic_score
            for i, base in enumerate(base_logits)
        ]

    def predict(
        self,
        base_logits: Sequence[float],
        symbolic_score: float,
    ) -> Tuple[int, List[float]]:
        logits = self.logits(base_logits, symbolic_score)
        probabilities = softmax(logits)
        return argmax(probabilities), probabilities


# ============================================================================
# 5. Reference trainer
# ============================================================================

class ReferenceTrainer:
    """Train the small reference model with explicit scalar updates."""

    def __init__(
        self,
        model: ReferenceNeuroSymbolicModel,
        config: Optional[TrainerConfig] = None,
    ) -> None:
        self.model = model
        self.config = config or TrainerConfig()
        self.state = TrainingState()

    @staticmethod
    def symbolic_score(example: TrainingExample) -> float:
        if not example.symbolic_bias:
            return 0.0
        non_zero = [
            abs(value)
            for row in example.symbolic_bias
            for value in row
            if abs(value) > 1e-12
        ]
        if not non_zero:
            return 0.0
        return min(1.0, sum(non_zero) / (len(non_zero) * 5.0))

    def _target_index(self, example: TrainingExample) -> int:
        target = (example.target or "").strip().lower()
        if target in self.model.index:
            return self.model.index[target]

        # Deterministic fallback: hash target/text into the toy vocabulary.
        source = target or example.text
        return int.from_bytes(source.encode("utf-8"), "little") % len(self.model.vocabulary)

    def _base_logits(self, example: TrainingExample) -> List[float]:
        # A deterministic pseudo-feature extractor. The real LLM replaces this
        # with hidden states from a neural backbone.
        digest = sum(ord(char) for char in example.text)
        return [
            math.sin(digest * 0.001 + i) * 0.1
            for i in range(len(self.model.vocabulary))
        ]

    def train_example(self, example: TrainingExample) -> Tuple[float, float, int]:
        base = self._base_logits(example)
        symbolic = self.symbolic_score(example) * self.config.symbolic_bias_scale
        target = self._target_index(example)

        logits = self.model.logits(base, symbolic * self.model.bias_gate)
        probabilities = softmax(logits)
        loss = cross_entropy(probabilities, target)

        # Derivative of CE w.r.t. the shared symbolic gate. Since the symbolic
        # score is a scalar added equally to every class in this toy model,
        # its gradient is zero. We therefore use a contrastive symbolic score
        # below: positive symbolic evidence is treated as a target-dependent
        # prior. This keeps the toy trainer mathematically meaningful.
        symbolic_prior = [
            symbolic if i == target else 0.0
            for i in range(len(probabilities))
        ]
        prior_logits = [
            logits[i] + symbolic_prior[i]
            for i in range(len(logits))
        ]
        prior_probabilities = softmax(prior_logits)
        symbolic_loss = cross_entropy(prior_probabilities, target)

        gradient = [
            probability - (1.0 if i == target else 0.0)
            for i, probability in enumerate(prior_probabilities)
        ]

        lr = self.config.learning_rate
        for i in range(len(self.model.token_bias)):
            self.model.token_bias[i] -= lr * clip(
                gradient[i],
                self.config.gradient_clip,
            )

        gate_gradient = -symbolic * max(0.0, 1.0 - prior_probabilities[target])
        self.model.bias_gate -= lr * clip(
            gate_gradient,
            self.config.gradient_clip,
        )

        predicted = argmax(prior_probabilities)
        return loss, symbolic_loss, int(predicted == target)

    def train(
        self,
        examples: Sequence[TrainingExample],
        checkpoint_dir: Optional[str | Path] = None,
    ) -> TrainingState:
        if not examples:
            raise ValueError("training set is empty")

        for epoch in range(1, self.config.epochs + 1):
            losses: List[float] = []
            symbolic_losses: List[float] = []
            correct = 0
            attention_masses: List[float] = []

            for example in examples:
                loss, symbolic_loss, is_correct = self.train_example(example)
                losses.append(loss)
                symbolic_losses.append(symbolic_loss)
                correct += is_correct
                self.state.step += 1

                if example.symbolic_bias:
                    attention = row_softmax(
                        example.symbolic_bias
                    )
                    attention_masses.append(
                        attention_mass_on_symbolic_edges(
                            attention,
                            example.symbolic_bias,
                        )
                    )

            metric = TrainingMetrics(
                epoch=epoch,
                loss=sum(losses) / len(losses),
                symbolic_loss=sum(symbolic_losses) / len(symbolic_losses),
                baseline_loss=sum(losses) / len(losses),
                accuracy=correct / len(examples),
                symbolic_attention_mass=(
                    sum(attention_masses) / len(attention_masses)
                    if attention_masses else 0.0
                ),
            )

            self.state.epoch = epoch
            self.state.history.append(metric)
            self.state.best_loss = min(
                self.state.best_loss,
                metric.loss,
            )

            if checkpoint_dir and (
                epoch % self.config.checkpoint_every == 0
                or epoch == self.config.epochs
            ):
                self.save_checkpoint(
                    Path(checkpoint_dir) / f"checkpoint_epoch_{epoch}.json"
                )

        return self.state

    def save_checkpoint(self, path: str | Path) -> Path:
        destination = Path(path)
        destination.parent.mkdir(parents=True, exist_ok=True)
        payload = {
            "format": "panini_neuro_symbolic_reference_checkpoint_v1",
            "config": self.config.to_dict(),
            "state": self.state.to_dict(),
            "model": {
                "vocabulary": self.model.vocabulary,
                "bias_gate": self.model.bias_gate,
                "token_bias": self.model.token_bias,
            },
        }
        destination.write_text(
            json.dumps(payload, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
        return destination


# ============================================================================
# 6. Transformer-ready batch contract
# ============================================================================

@dataclass
class TransformerBatch:
    input_ids: Any
    attention_mask: Any
    symbolic_bias: Any
    labels: Any
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "input_ids": self.input_ids,
            "attention_mask": self.attention_mask,
            "symbolic_bias": self.symbolic_bias,
            "labels": self.labels,
            "metadata": self.metadata,
        }


def build_transformer_batch(
    examples: Sequence[TrainingExample],
    tokenizer: Any,
    pad_token_id: int = 0,
) -> TransformerBatch:
    """
    Build a generic batch from a HuggingFace-compatible tokenizer.

    tokenizer is intentionally injected. This keeps File 11 independent of a
    specific tokenizer/model family.
    """
    if not examples:
        raise ValueError("examples cannot be empty")

    texts = [example.text for example in examples]
    encoded = tokenizer(
        texts,
        padding=True,
        truncation=True,
        return_tensors="pt",
    )

    input_ids = encoded["input_ids"]
    attention_mask = encoded["attention_mask"]
    batch_size, sequence_length = input_ids.shape

    # Symbolic bias matrices are created over source tokens. A real tokenizer
    # may split words into subwords; mapping from word indices to subword spans
    # is therefore left as an explicit future extension instead of silently
    # assuming 1:1 alignment.
    symbolic_bias = []
    for example in examples:
        if example.symbolic_bias is None:
            symbolic_bias.append([
                [0.0] * sequence_length
                for _ in range(sequence_length)
            ])
            continue

        source = example.symbolic_bias
        resized = [
            row[:sequence_length]
            + [0.0] * max(0, sequence_length - len(row))
            for row in source[:sequence_length]
        ]
        while len(resized) < sequence_length:
            resized.append([0.0] * sequence_length)
        symbolic_bias.append(resized)

    try:
        import torch
        symbolic_bias_tensor = torch.tensor(
            symbolic_bias,
            dtype=torch.float32,
            device=input_ids.device,
        ).unsqueeze(1)
    except ImportError:
        symbolic_bias_tensor = symbolic_bias

    labels = input_ids.clone() if hasattr(input_ids, "clone") else input_ids

    return TransformerBatch(
        input_ids=input_ids,
        attention_mask=attention_mask,
        symbolic_bias=symbolic_bias_tensor,
        labels=labels,
        metadata={
            "batch_size": batch_size,
            "sequence_length": sequence_length,
            "symbolic_alignment": "conservative_word_to_token_crop",
            "pad_token_id": pad_token_id,
        },
    )


# ============================================================================
# 7. Optional PyTorch attention module
# ============================================================================

class SymbolicAttentionAdapter:
    """Optional PyTorch module for adding learnable symbolic bias."""

    def __init__(self, initial_scale: float = 1.0) -> None:
        try:
            import torch
            import torch.nn as nn
        except ImportError as exc:
            raise RuntimeError(
                "PyTorch is required for SymbolicAttentionAdapter"
            ) from exc

        self.torch = torch
        self.nn = nn
        self.module = nn.Module()
        self.scale = nn.Parameter(
            torch.tensor(float(initial_scale))
        )

    def parameters(self):
        return [self.scale]

    def forward(self, logits: Any, symbolic_bias: Any) -> Any:
        bias = symbolic_bias
        if bias.ndim == 2:
            bias = bias.unsqueeze(0).unsqueeze(0)
        elif bias.ndim == 3:
            bias = bias.unsqueeze(1)
        return logits + self.scale * bias


# ============================================================================
# 8. Full training architecture specification
# ============================================================================

@dataclass
class TrainingArchitecture:
    tokenizer: str = "external / injected"
    lexical_encoder: str = "Transformer or embedding model"
    symbolic_encoder: str = "File 10 Paninian English representation"
    fusion: str = "additive attention bias + optional learned gate"
    objective: str = "next-token prediction / task loss"
    regularization: str = "symbolic consistency loss (optional)"
    checkpointing: str = "JSON reference / framework checkpoint in production"

    def to_dict(self) -> Dict[str, str]:
        return asdict(self)


def architecture_spec() -> Dict[str, Any]:
    return {
        "architecture": TrainingArchitecture().to_dict(),
        "data_flow": [
            "raw text",
            "tokenizer",
            "Paninian symbolic analyzer",
            "token embeddings",
            "symbolic attention bias",
            "Transformer attention",
            "hidden states",
            "prediction head",
            "language-model loss",
            "backpropagation",
        ],
        "research_hypotheses": [
            "symbolic structure can improve sample efficiency",
            "symbolic bias can reduce attention search space",
            "learned gates can prevent over-reliance on symbolic heuristics",
            "uncertain symbolic relations should remain probabilistic",
        ],
        "known_limits": [
            "File 10 uses a heuristic English analyzer",
            "word-to-subword alignment requires a tokenizer-aware mapper",
            "reference trainer is not a production LLM optimizer",
            "symbolic rules need empirical evaluation against learned baselines",
        ],
    }


# ============================================================================
# 9. Dataset helpers
# ============================================================================

def save_jsonl(
    examples: Sequence[TrainingExample],
    path: str | Path,
) -> Path:
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    with destination.open("w", encoding="utf-8") as handle:
        for example in examples:
            handle.write(
                json.dumps(
                    example.to_dict(),
                    ensure_ascii=False,
                )
                + "\n"
            )
    return destination


def make_demo_dataset() -> List[TrainingExample]:
    builder = SymbolicBatchBuilder()
    pairs = [
        ("Rama reads the book.", "book"),
        ("Rama writes with a pen.", "pen"),
        ("Rama gives a book to Sita.", "sita"),
        ("Rama builds a book with a knife.", "book"),
        ("Rama writes a book in Mumbai.", "book"),
    ]
    return [
        builder.from_text(text, target=target)
        for text, target in pairs
    ]


# ============================================================================
# 10. CLI rendering
# ============================================================================

def render_training_summary(
    state: TrainingState,
    model: ReferenceNeuroSymbolicModel,
) -> str:
    lines = [
        "=" * 96,
        "PANINI NEURO-SYMBOLIC TRAINER",
        "=" * 96,
        f"epochs: {state.epoch}",
        f"steps: {state.step}",
        f"best loss: {state.best_loss:.6f}",
        f"learned symbolic gate: {model.bias_gate:.6f}",
        "",
        "TRAINING HISTORY",
        "-" * 96,
    ]

    for metric in state.history:
        lines.append(
            f"epoch={metric.epoch:03d} "
            f"loss={metric.loss:.6f} "
            f"symbolic_loss={metric.symbolic_loss:.6f} "
            f"accuracy={metric.accuracy:.3f} "
            f"symbolic_attention_mass={metric.symbolic_attention_mass:.3f}"
        )

    return "\n".join(lines)


# ============================================================================
# 11. Self-test
# ============================================================================

def self_test() -> None:
    # Numerical tests.
    probabilities = softmax([0.0, 1.0, 2.0])
    assert len(probabilities) == 3
    assert abs(sum(probabilities) - 1.0) < 1e-9
    assert probabilities[2] > probabilities[1] > probabilities[0]

    loss = cross_entropy(probabilities, 2)
    assert loss > 0

    # Symbolic preprocessing.
    builder = SymbolicBatchBuilder()
    example = builder.from_text(
        "Rama reads the book.",
        target="book",
    )

    assert example.text == "Rama reads the book."
    assert example.symbolic_bias is not None
    assert len(example.symbolic_bias) > 0

    # Reference model/training.
    vocabulary = [
        "book",
        "pen",
        "sita",
        "mumbai",
    ]
    model = ReferenceNeuroSymbolicModel(
        vocabulary,
        seed=7,
    )
    config = TrainerConfig(
        epochs=3,
        learning_rate=0.02,
        checkpoint_every=3,
        seed=7,
    )
    trainer = ReferenceTrainer(model, config)
    dataset = make_demo_dataset()
    state = trainer.train(dataset)

    assert state.epoch == 3
    assert state.step == 15
    assert len(state.history) == 3
    assert math.isfinite(state.best_loss)

    # Checkpoint round-trip existence/content.
    checkpoint = Path("_panini_test_checkpoint.json")
    try:
        trainer.save_checkpoint(checkpoint)
        assert checkpoint.exists()
        payload = json.loads(
            checkpoint.read_text(encoding="utf-8")
        )
        assert payload["format"].startswith(
            "panini_neuro_symbolic_reference"
        )
        assert "model" in payload
    finally:
        if checkpoint.exists():
            checkpoint.unlink()

    # Attention-bias integration.
    logits = [
        [0.0, 0.0],
        [0.0, 0.0],
    ]
    bias = [
        [0.0, 4.0],
        [2.0, 0.0],
    ]
    combined = matrix_add(logits, bias)
    attention = row_softmax(combined)
    assert attention[0][1] > attention[0][0]
    assert attention[1][0] > attention[1][1]

    mass = attention_mass_on_symbolic_edges(
        attention,
        bias,
    )
    assert 0.0 <= mass <= 1.0

    # Architecture contract.
    spec = architecture_spec()
    assert "architecture" in spec
    assert "data_flow" in spec
    assert len(spec["data_flow"]) >= 5

    # JSONL helper.
    jsonl = Path("_panini_test.jsonl")
    try:
        save_jsonl(dataset[:2], jsonl)
        loaded = builder.load_jsonl(jsonl)
        assert len(loaded) == 2
        assert loaded[0].text == dataset[0].text
    finally:
        if jsonl.exists():
            jsonl.unlink()


# ============================================================================
# 12. CLI
# ============================================================================

def build_cli() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="neuro_symbolic_trainer",
        description="Train and test the Panini neuro-symbolic reference model.",
    )
    parser.add_argument(
        "--data",
        metavar="JSONL",
        help="JSONL training data. If omitted, use demo data.",
    )
    parser.add_argument(
        "--epochs",
        type=int,
        default=10,
    )
    parser.add_argument(
        "--lr",
        type=float,
        default=0.01,
    )
    parser.add_argument(
        "--checkpoint-dir",
        default="panini_checkpoints",
    )
    parser.add_argument(
        "--architecture",
        action="store_true",
        help="Print the training architecture contract.",
    )
    parser.add_argument(
        "--self-test",
        action="store_true",
    )
    return parser


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = build_cli().parse_args(argv)

    if args.self_test:
        self_test()
        print("SELF_TEST_PASS")
        return 0

    if args.architecture:
        print(json.dumps(architecture_spec(), indent=2, ensure_ascii=False))
        if not args.data:
            return 0

    builder = SymbolicBatchBuilder()
    examples = (
        builder.load_jsonl(args.data)
        if args.data
        else make_demo_dataset()
    )

    vocabulary = sorted({
        (example.target or "unknown").strip().lower()
        for example in examples
    })
    if not vocabulary:
        vocabulary = ["unknown"]

    model = ReferenceNeuroSymbolicModel(
        vocabulary=vocabulary,
        seed=42,
    )
    config = TrainerConfig(
        epochs=args.epochs,
        learning_rate=args.lr,
    )
    trainer = ReferenceTrainer(
        model,
        config,
    )
    state = trainer.train(
        examples,
        checkpoint_dir=args.checkpoint_dir,
    )

    print(
        render_training_summary(
            state,
            model,
        )
    )

    return 0


if __name__ == "__main__":
    main()
